import type { CharacterCard } from "./types";

// Personnages très reconnaissables, issus de séries encore populaires. Les
// images sont cherchées côté navigateur via AniList ; la partie reste jouable
// avec le nom et l'anime si le service d'images est indisponible.
const RAW_CHARACTERS: Array<[string, string]> = [
  ["Monkey D. Luffy", "One Piece"],
  ["Roronoa Zoro", "One Piece"],
  ["Nami", "One Piece"],
  ["Sanji", "One Piece"],
  ["Naruto Uzumaki", "Naruto"],
  ["Sasuke Uchiha", "Naruto"],
  ["Sakura Haruno", "Naruto"],
  ["Kakashi Hatake", "Naruto"],
  ["Ichigo Kurosaki", "Bleach"],
  ["Rukia Kuchiki", "Bleach"],
  ["Satoru Gojo", "Jujutsu Kaisen"],
  ["Yuji Itadori", "Jujutsu Kaisen"],
  ["Megumi Fushiguro", "Jujutsu Kaisen"],
  ["Nobara Kugisaki", "Jujutsu Kaisen"],
  ["Tanjiro Kamado", "Demon Slayer"],
  ["Nezuko Kamado", "Demon Slayer"],
  ["Zenitsu Agatsuma", "Demon Slayer"],
  ["Inosuke Hashibira", "Demon Slayer"],
  ["Eren Yeager", "Attack on Titan"],
  ["Mikasa Ackerman", "Attack on Titan"],
  ["Levi Ackerman", "Attack on Titan"],
  ["Denji", "Chainsaw Man"],
  ["Power", "Chainsaw Man"],
  ["Makima", "Chainsaw Man"],
  ["Anya Forger", "SPY x FAMILY"],
  ["Loid Forger", "SPY x FAMILY"],
  ["Yor Forger", "SPY x FAMILY"],
  ["Izuku Midoriya", "My Hero Academia"],
  ["Katsuki Bakugo", "My Hero Academia"],
  ["Shoto Todoroki", "My Hero Academia"],
  ["Gon Freecss", "Hunter x Hunter"],
  ["Killua Zoldyck", "Hunter x Hunter"],
  ["Hisoka Morow", "Hunter x Hunter"],
  ["Goku", "Dragon Ball"],
  ["Vegeta", "Dragon Ball"],
  ["Saitama", "One Punch Man"],
  ["Genos", "One Punch Man"],
  ["Frieren", "Frieren"],
  ["Fern", "Frieren"],
  ["Maomao", "The Apothecary Diaries"],
  ["Jinshi", "The Apothecary Diaries"],
  ["Sung Jin-Woo", "Solo Leveling"],
  ["Kafka Hibino", "Kaiju No. 8"],
  ["Rin Itoshi", "Blue Lock"],
  ["Yoichi Isagi", "Blue Lock"],
  ["Shoyo Hinata", "Haikyuu!!"],
  ["Tobio Kageyama", "Haikyuu!!"],
  ["Senku Ishigami", "Dr. Stone"],
  ["Asta", "Black Clover"],
  ["Yuno", "Black Clover"],
  ["Subaru Natsuki", "Re:Zero"],
  ["Emilia", "Re:Zero"],
  ["Rem", "Re:Zero"],
  ["Aqua", "KonoSuba"],
  ["Megumin", "KonoSuba"],
  ["Lelouch Lamperouge", "Code Geass"],
  ["Light Yagami", "Death Note"],
  ["L Lawliet", "Death Note"],
  ["Edward Elric", "Fullmetal Alchemist"],
  ["Alphonse Elric", "Fullmetal Alchemist"],

  // Autres figures populaires des grandes licences.
  ["Trafalgar Law", "One Piece"],
  ["Nico Robin", "One Piece"],
  ["Shanks", "One Piece"],
  ["Hinata Hyuga", "Naruto"],
  ["Gaara", "Naruto"],
  ["Itachi Uchiha", "Naruto"],
  ["Madara Uchiha", "Naruto"],
  ["Sosuke Aizen", "Bleach"],
  ["Orihime Inoue", "Bleach"],
  ["Yuta Okkotsu", "Jujutsu Kaisen"],
  ["Ryomen Sukuna", "Jujutsu Kaisen"],
  ["Toji Fushiguro", "Jujutsu Kaisen"],
  ["Suguru Geto", "Jujutsu Kaisen"],
  ["Kyojuro Rengoku", "Demon Slayer"],
  ["Giyu Tomioka", "Demon Slayer"],
  ["Shinobu Kocho", "Demon Slayer"],
  ["Muzan Kibutsuji", "Demon Slayer"],
  ["Armin Arlert", "Attack on Titan"],
  ["Erwin Smith", "Attack on Titan"],
  ["All Might", "My Hero Academia"],
  ["Ochaco Uraraka", "My Hero Academia"],
  ["Dabi", "My Hero Academia"],
  ["Kurapika", "Hunter x Hunter"],
  ["Chrollo Lucilfer", "Hunter x Hunter"],
  ["Gohan", "Dragon Ball"],
  ["Piccolo", "Dragon Ball"],
  ["Frieza", "Dragon Ball"],

  // Héros de séries récentes et toujours très suivies.
  ["Momo Ayase", "Dandadan"],
  ["Ken Takakura", "Dandadan"],
  ["Aira Shiratori", "Dandadan"],
  ["Seiko Ayase", "Dandadan"],
  ["Laios Touden", "Delicious in Dungeon"],
  ["Marcille Donato", "Delicious in Dungeon"],
  ["Senshi", "Delicious in Dungeon"],
  ["Ai Hoshino", "Oshi no Ko"],
  ["Ruby Hoshino", "Oshi no Ko"],
  ["Aquamarine Hoshino", "Oshi no Ko"],
  ["Kana Arima", "Oshi no Ko"],
  ["Taro Sakamoto", "Sakamoto Days"],
  ["Shin Asakura", "Sakamoto Days"],
  ["Nagumo", "Sakamoto Days"],
  ["Mash Burnedead", "Mashle"],
  ["Gabimaru", "Hell's Paradise"],
  ["Yamada Asaemon Sagiri", "Hell's Paradise"],
  ["Hitori Gotoh", "Bocchi the Rock!"],
  ["Marin Kitagawa", "My Dress-Up Darling"],
  ["David Martinez", "Cyberpunk: Edgerunners"],
  ["Lucyna Kushinada", "Cyberpunk: Edgerunners"],
  ["Meguru Bachira", "Blue Lock"],
  ["Seishiro Nagi", "Blue Lock"],
  ["Shoei Baro", "Blue Lock"],
  ["Mina Ashiro", "Kaiju No. 8"],
  ["Soshiro Hoshina", "Kaiju No. 8"],
  ["Cha Hae-In", "Solo Leveling"],
  ["Himmel", "Frieren"],
  ["Stark", "Frieren"],
  ["Reze", "Chainsaw Man"],
  ["Aki Hayakawa", "Chainsaw Man"],
  ["Thorfinn", "Vinland Saga"],
  ["Reigen Arataka", "Mob Psycho 100"],
];

export const CHARACTERS: CharacterCard[] = RAW_CHARACTERS.map(([name, anime], index) => ({
  id: `character-${index + 1}`,
  name,
  anime,
}));
